### PR TITLE
Fixing a couple of things on the callout and breadcrumb pages

### PR DESCRIPTION
**Pull request by alexcolbeck1**
## Checklist
- [ ] Design and code examples added to the Design System pages
- [ ] Changes added to [CHANGELOG.md](../CHANGELOG.md)
- [ ] Successful linting of the SCSS (`npm run lint-css`)

### CODE REVIEW

**Review by chrimesdev — CHANGES_REQUESTED** [review]
Changes as discussed

**Review by alexcolbeck1 — COMMENTED** [review]
Changes made

**Comment by alexcolbeck1** [comment]
Changes made and conflict with `router.js` should be resolved.

**Comment by chrimesdev** [comment]
@alexcolbeck1 Do we need to update the breadcrumb on every example page? Currently the breadcrumb on some example pages isn't in the new format and they break (by going blank/empty) when you reach the mobile breakpoint.

Also need to update your branch with master, still some conflicts to resolve with router.js

**Comment by alexcolbeck1** [comment]
Superseded by request #60

**Pull request closed without merging**
