### PR TITLE
SVG icons fallbacks & accessibility

### PR DESCRIPTION
**Pull request by chrimesdev**
## Description
Use the NHS SVG logo with a PNG fallback in the header & footer. 
Update some dependencies.
Remove some unused files and folders.

## Checklist
- [ ] Design and code examples added to the Design System pages
- [ ] Changes added to [CHANGELOG.md](../CHANGELOG.md)
- [X] Successful linting of the SCSS (`npm run lint-css`)

### CODE REVIEW

**Review by mcheung-nhs — CHANGES_REQUESTED** [review]
Header logo now not showing. Could you do the same changes that have been done in the footer?

**Comment by chrimesdev** [comment]
@mcheung-nhs changes made. 

Not sure why deployment is failing, the Travis build is passing.

**Comment by mcheung-nhs** [comment]
@AdamChrimes 
Error log:

-----> Building dependencies
       Installing node modules (package.json + package-lock)
       npm ERR! path /tmp/build_94aeb3cbf620dfc1383fca81f8a74dbd/node_modules/npm/node_modules/dezalgo
       npm ERR! code ENOENT
       npm ERR! errno -2
       npm ERR! syscall rename
       npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/build_94aeb3cbf620dfc1383fca81f8a74dbd/node_modules/npm/node_modules/dezalgo' -> '/tmp/build_94aeb3cbf620dfc1383fca81f8a74dbd/node_modules/npm/node_modules/.dezalgo.DELETE'
       npm ERR! enoent This is related to npm not being able to find a file.
       npm ERR! enoent       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.LabIF/_logs/2018-06-27T18_14_41_712Z-debug.log
-----> Build failed

**Comment by chrimesdev** [comment]
@mcheung-nhs all sorted now

**Review by mcheung-nhs — APPROVED** [review]

**Pull request merged**
