### PR TITLE
Use curly not straight apostrophe on homepage

### PR DESCRIPTION
**Pull request by quis**
> “Smart quotes,” the correct quotation marks and apostrophes, are curly or sloped. […] straight quotes are a vestigial constraint from typewriters when using one key for two different marks helped save space on a keyboard.<sup>1</sup>

This pull request replaces the use of a straight single quotation mark as an apostrophe with the typographically-correct equivalent:

Before | After 
---|---
image | image

1. http://smartquotesforsmartpeople.com

### CODE REVIEW

**Comment by chrimesdev** [comment]
Hi @quis thanks for opening a pull request (our first non NHS contributor!)

I've checked this with the content team and they've come back to me and said; 

> generally the curly apostrophe is typographically correct, but we've always used the straight one on the NHS website. This can be found in our Digital service manual https://beta.nhs.uk/service-manual/content-style-guide/formatting-and-punctuation/#apostrophes

I'll try and find out the rationale behind this, as there is none in the NHS Digital service manual.

**Comment by deanvipondNHS** [comment]
Thanks for this @quis – agree completely, and it's on our backlog to address. Regarding it being in the content guidelines, this is going to be amended.

**Comment by chrimesdev** [comment]
Hi @quis 

This change has been made on the live website https://www.nhs.uk/

We're in the process of making sure we use curly not straight apostrophes across the website and are making changes to the service manual to reflect this.

Thanks for raising this!

**Review by chrimesdev — APPROVED** [review]

**Comment by quis** [comment]
@AdamChrimes that’s so cool, thanks for taking the time to follow through on this (and the great work your team is doing in general).

**Pull request merged**
